version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: ocr_service:${OCR_SERVICE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      OCR_SERVICE_HOST: 0.0.0.0
